### ISSUE TITLE
Redesign as single-column layout

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/p3k#90]
Get rid of the sidebar

Move things to header/footer instead

Not sure what to do about the home page yet

**Comment by snarfed** [comment]
+1 to minimal w/o sidebar. it's obviously subjective, but i did it 2y ago with my site and i'm happy with it. before/after pics in https://snarfed.org/2013-06-16_redesigned . (the sidebar links went into header icons and text. the prose header is quirky, but works for me.)

**Comment by aaronpk** [comment]
New site has a single column layout!
